// <auto-generated />
namespace CIS_264_Price_APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HolidayClasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HolidayClasses));
        
        string IMigrationMetadata.Id
        {
            get { return "202111152024540_HolidayClasses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
